version: "3.8"

services:
  db:
    build:
      context: .            # корень вашего проекта
      dockerfile: Dockerfile
    restart: always
    container_name: erziback_db
    environment:
      POSTGRES_USER:     appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB:       erziapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # здесь ваш сервис (api), minio, kafka и т.д.
  # …

volumes:
  pgdata:
